### ISSUE TITLE
Unable to sign in 

### ISSUE THREAD

**Issue by ajeetraina** [rajkram/greenearth#1]
I was able to bring up the application but it doesn't allow me to sign up or login. Any idea?

Here's the details:

```
$ docker run -d -p 6379:6379 redislabs/redismod
Unable to find image 'redislabs/redismod:latest' locally
latest: Pulling from redislabs/redismod
8559a31e96f4: Pull complete 
c617de782a2a: Pull complete 
58b53decd086: Pull complete 
e99d6ee25bd1: Pull complete 
3ef46d6fa932: Pull complete 
78be60a8ee88: Pull complete 
3af49d6f0bef: Pull complete 
6612ecb3fbbc: Pull complete 
d082658e00d8: Pull complete 
6921b2fd8601: Pull complete 
0528ff6bd173: Pull complete 
61069bb18c7d: Pull complete 
7d5a732d89e4: Pull complete 
d71d41129e17: Pull complete 
c6c22e3f782c: Pull complete 
4b2689e9a012: Pull complete 
d30721eb6546: Pull complete 
ae37fa0559dd: Pull complete 
769984b41cc9: Pull complete 
d40984294091: Pull complete 
fdc3c4c8c4d9: Pull complete 
813ae032bbaa: Pull complete 
b56136997a65: Pull complete 
189ebfa42e41: Pull complete 
ae6ff1e6a35d: Pull complete 
4ba4ea695340: Pull complete 
Digest: sha256:b99fc9f531fbbd3951dfcb32b37d2b15626ad385a2cd7e03ec0e728c2caf5e1b
Status: Downloaded newer image for redislabs/redismod:latest
6a5722857525dcaae5def22df0d41fc60d2e9809f1672a7220a2cc01841fd3e2
[node1] (local) root@192.168.0.27 ~/greenearth
$ npm start 

> Redis.js@1.0.0 start /root/greenearth
> node index.js

Example app listening at http://localhost:3000
node_redis: Warning: Redis server does not require a password, but a password was supplied.
```
<img width="1771" alt="Screen Shot 2021-07-15 at 1 48 02 PM" src="https://user-images.githubusercontent.com/313480/125754204-50813a14-ea10-47b8-b4a2-7bce22d7a7dc.png">

**Comment by rajkram** [comment]
Hi Ajeet, 
Did you enable the RedisJSON module on your local redis instance running on docker? 
We only tried connecting to a Redis Cloud Enterprise DB with that module turned on to connect and make the app work for the hackathon.
Please let me know. If needed, I will try to reproduce locally.

**Comment by ajeetraina** [comment]
@rajkram Yes, it is working with Redis Enterprise CLoud. I am able to access the site.
But when I try to create a new post or access old posts:

```
Example app listening at http://localhost:3000
Not authenticated.
{ posts: [] }
Not authenticated.
{ posts: [] }
Not authenticated.
{ posts: [] }
Not authenticated.
Not authenticated.
(node:2755) UnhandledPromiseRejectionWarning: Error: node_redis: The JSON.GET command contains a invalid argument type.
Only strings, dates and buffers are accepted. Please update your code to use valid argument types.
    at RedisClient.internal_send_command (/Users/ajeetraina/marketplace/greenearth/node_modules/redis/index.js:835:39)
    at RedisClient.json_get (/Users/ajeetraina/marketplace/greenearth/node_modules/redis/lib/commands.js:46:25)
    at internal/util.js:308:30
    at new Promise (<anonymous>)
    at RedisClient.json_get (internal/util.js:307:12)
    at /Users/ajeetraina/marketplace/greenearth/index.js:121:20
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Not authenticated.
{ posts: [] }
Not authenticated.
{ posts: [] }


```
Can you help us with the below details:
- Architecture
- How the data is accessed
- How the data is stored

It would be great if you can put the above info under README.

**Comment by rajkram** [comment]
@ajeetraina Sure will do soon.
